"""
One place for every folder the pipeline reads from or writes to, so no
script hard-codes a path.

Expected repository layout (this file lives in <repo>/src/):

    <repo>/
      metadata/station_reference.csv   station IDs, coordinates, timezone, availability
      raw_data/                        original downloads, never edited
        epa/     cork/  dublin/dublinRathmines/  …   (which folder belongs to which
        uk_air/  belfast/  london/londonBloomsbury/ …  station is set by the raw_folder
        eea/     athens/athensAristotelous/  …            column in station_reference.csv)
      processed_data/                  everything the pipeline generates (git-ignored;
                                       the versioned copies live in GCS)
      src/                             these scripts

Paths are anchored to the repository, not to the folder you happen to run
from, so `python src/canonicalize_raw_data.py` works from anywhere.

Also here: PIPELINE_VERSION and git_commit() (both written into every
manifest record) and check_gcp_settings() (stops the two GCS scripts with a
clear message if the project and bucket have not been set).
"""
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent   # this file is <repo>/src/config.py, so two levels up is the repo

# Folders used by the pipeline (all inside the repository)
METADATA_DIR = REPO_ROOT / "metadata"
RAW_DIR = REPO_ROOT / "raw_data"                # original downloads, never edited
PROCESSED_DIR = REPO_ROOT / "processed_data"    # generated by the pipeline (git-ignored)

REFERENCE_PATH = METADATA_DIR / "station_reference.csv"   # the station table every script reads


def check_gcp_settings(project_id: str, bucket_name: str) -> None:
    """Stop early, with a clear message, if the project/bucket are still the placeholders."""
    if project_id.startswith("your-") or bucket_name.startswith("your-"):
        raise SystemExit("GCP_PROJECT_ID and GCS_BUCKET_NAME are not set. Set them as environment variables "
                         "(PowerShell: $env:GCP_PROJECT_ID=\"...\"; $env:GCS_BUCKET_NAME=\"...\") and run again.")


# Bump this when the pipeline's behaviour changes. It is written into every manifest record.
PIPELINE_VERSION = "v1"


def git_commit() -> str:
    """Hash of the code that is running, for the manifests. Gets a "-dirty" suffix
    if tracked files have uncommitted changes, and "unknown" outside a git repo."""
    try:
        # "git rev-parse HEAD" prints the hash of the current commit
        sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, capture_output=True, text=True, timeout=10)
        if sha.returncode != 0 or not sha.stdout.strip():
            return "unknown"   # not a git repository
        # "status --porcelain" lists modified tracked files; untracked files are ignored,
        # so only uncommitted edits to committed files make the run "dirty"
        changed = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no"], cwd=REPO_ROOT,
                                 capture_output=True, text=True, timeout=10).stdout.strip()
        return sha.stdout.strip() + ("-dirty" if changed else "")
    except Exception:   # git missing or timed out: never let this stop a pipeline run
        return "unknown"
